@extends('marketing.plantilla.plantilla')
@section('contenido')   
	
	<section class="hero-section">
		<div class="hero-slider owl-carousel">			
			<div class="hs-item" style="padding-top:38px; padding-bottom: 80px; height: auto !important; background-position: top center; ">
				<div class="container">
					<div class="row">
						<div class="col-lg-12" style="text-align: center;">							
					
							<h1 style="font-size: 48px; color: #fff; margin-top: 100px;">Términos de Uso</h1>
				
						</div>						
					</div>
				</div>
			</div>
		</div>
	</section>


	<!-- Intro section -->
	<section class="intro-section spad">
		<div class="container">
			<div class="row">				
				<div class="col-lg-12">

<p><em>Estas Condiciones de uso (<strong>&ldquo;Condiciones&rdquo;</strong>) se actualizaron por &uacute;ltima vez el Mayo 15, 2018.</em></p>
<p>La misi&oacute;n de Udemy es mejorar la vida de las personas mediante el aprendizaje. Permitimos que cualquier persona pueda crear y compartir cursos educativos (instructores), e inscribirse en estos cursos educativos para aprender (estudiantes) en cualquier parte del mundo. Creemos que nuestro modelo de tienda virtual es la mejor manera de ofrecer contenido educativo valioso a nuestros usuarios. Necesitamos reglas que mantengan nuestra plataforma y nuestros servicios seguros para usted, para nosotros, para nuestros estudiantes y para nuestra comunidad de instructores. Estas Condiciones se aplican a todas las actividades que lleva a cabo en el sitio web de Udemy, las aplicaciones m&oacute;viles de Udemy, nuestras aplicaciones de TV, nuestras API y todos los dem&aacute;s servicios relacionados (<strong>&ldquo;Servicios&rdquo;</strong>).</p>
<p>Si publica un curso en la plataforma de Udemy, tambi&eacute;n debe aceptar el&nbsp;<a href="https://www.udemy.com/terms/instructor/">Acuerdo de instructor</a>. Tambi&eacute;n proporcionamos detalles relacionados con el procesamiento de los datos personales de nuestros estudiantes e instructores en nuestra&nbsp;<a href="https://www.udemy.com/terms/privacy/">Pol&iacute;tica de privacidad</a>. Si utiliza Udemy como parte de nuestro programa de aprendizaje y desarrollo Udemy For Business (UFB), puedes consultar nuestra&nbsp;<a href="https://www.udemy.com/terms/ufb-privacy/">Declaraci&oacute;n de privacidad de UFB</a>.</p>
<p><strong>Si vive en Estados Unidos o Canad&aacute;, y declara su conformidad con estas Condiciones, acepta resolver los conflictos con Udemy mediante arbitraje vinculante (con excepciones muy limitadas, no en los tribunales). Adem&aacute;s, renuncia a determinados derechos de participaci&oacute;n en acciones de grupo, tal como se describe en la secci&oacute;n Resoluci&oacute;n de conflictos.</strong></p>
<p>&nbsp;</p>
<h2>&Iacute;ndice</h2>
<ul>
<li><a href="https://www.udemy.com/terms/#section1">1. Cuentas</a></li>
<li><a href="https://www.udemy.com/terms/#section2">2. Inscripci&oacute;n en un curso y acceso de por vida</a></li>
<li><a href="https://www.udemy.com/terms/#section3">3. Pagos, cr&eacute;ditos y reembolsos</a></li>
<li><a href="https://www.udemy.com/terms/#section4">4. Reglas de contenido y comportamiento</a></li>
<li><a href="https://www.udemy.com/terms/#section5">5. Derechos de Udemy respecto al contenido que publica</a></li>
<li><a href="https://www.udemy.com/terms/#section6">6. Utilizaci&oacute;n de Udemy por su cuenta y riesgo</a></li>
<li><a href="https://www.udemy.com/terms/#section7">7. Derechos de Udemy</a></li>
<li><a href="https://www.udemy.com/terms/#section8">8. Otras Condiciones legales</a></li>
<li><a href="https://www.udemy.com/terms/#section9">9. Resoluci&oacute;n de conflictos</a></li>
<li><a href="https://www.udemy.com/terms/#section10">10. Actualizaci&oacute;n de estas Condiciones</a></li>
<li><a href="https://www.udemy.com/terms/#section11">11. C&oacute;mo puede ponerse en contacto con nosotros</a></li>
</ul>
<h2 id="section1">1. Cuentas</h2>
<p>&nbsp;</p>
<div class="alert alert-info">
<div class="content">Necesita una cuenta para la mayor&iacute;a de las actividades que se llevan a cabo en nuestra plataforma. Guarde su contrase&ntilde;a de forma segura, porque deber&aacute; asumir la responsabilidad de todas las actividades asociadas con su cuenta. Si sospecha que alguien est&aacute; utilizando su cuenta, av&iacute;senos; para ello, p&oacute;ngase en contacto con nuestro&nbsp;<a href="https://www.udemy.com/support/">Equipo de soporte</a>. Para poder utilizar Udemy, deber&aacute; tener la mayor&iacute;a de edad establecida para el uso de los servicios online en su pa&iacute;s.</div>
</div>
<p>&nbsp;</p>
<p>Necesita una cuenta para la mayor&iacute;a de las actividades que se llevan a cabo en nuestra plataforma, incluidas las de comprar un curso, inscribirse en un curso o enviar un curso para su publicaci&oacute;n. Al configurar y mantener su cuenta, debe proporcionar en todo momento informaci&oacute;n precisa y completa, incluida una direcci&oacute;n de correo electr&oacute;nico v&aacute;lida. Asume toda la responsabilidad respecto a la cuenta y todo lo que sucede en ella, incluidos los da&ntilde;os o lesiones (que suframos nosotros o cualquier otra persona) causados por alguien que utilice su cuenta sin su permiso. Esto significa que debe tener cuidado con su contrase&ntilde;a. No puede transferir su cuenta a otra persona, ni utilizar la cuenta de otra persona sin su permiso. Si se pone en contacto con nosotros para solicitar el acceso a una cuenta, no se lo concederemos a menos que pueda proporcionarnos la informaci&oacute;n de las credenciales para iniciar sesi&oacute;n en dicha cuenta. Si un usuario fallece, su cuenta se cerrar&aacute;.</p>
<p>Si comparte sus credenciales para iniciar sesi&oacute;n en la cuenta con otra persona, asumir&aacute; toda la responsabilidad de lo que suceda con su cuenta, y Udemy no intervendr&aacute; en los conflictos que se puedan producir entre estudiantes e instructores que han compartido sus credenciales para iniciar sesi&oacute;n en la cuenta. Si descubre que otra persona puede estar utilizando su cuenta sin su permiso, o bien sospecha que se ha producido alguna otra infracci&oacute;n de seguridad, debe ponerse en contacto con el&nbsp;<a href="https://www.udemy.com/support/">Equipo de soporte</a>&nbsp;inmediatamente y comunic&aacute;rnoslo. Puede que le pidamos determinada informaci&oacute;n para confirmar que realmente es el propietario de la cuenta.</p>
<p>Los estudiantes e instructores deben tener al menos 18 a&ntilde;os para crear una cuenta en Udemy y utilizar los Servicios. Si a&uacute;n no tiene la edad necesaria, no puede configurar una cuenta, pero le animamos a que pida a uno de sus padres o a su tutor que abra una cuenta y le ayude a inscribirse en los cursos que son adecuados para usted. Si descubrimos que ha creado una cuenta y a&uacute;n no tiene la mayor&iacute;a de edad establecida para el uso de los servicios online (por ejemplo, 13 en EE. UU.), cancelaremos su cuenta. De conformidad con nuestro&nbsp;<a href="https://www.udemy.com/terms/instructor/">Acuerdo de instructor</a>, puede que se le solicite que confirme su identidad antes de recibir la autorizaci&oacute;n para enviar un curso para su publicaci&oacute;n en Udemy.</p>
<p>Puede cancelar su cuenta en cualquier momento; para ello, solo tiene que seguir los pasos que se muestran&nbsp;<a href="https://www.udemy.com/support/229603628/">aqu&iacute;</a>. Echa un vistazo a nuestra&nbsp;<a href="https://www.udemy.com/terms/privacy/">Pol&iacute;tica de privacidad</a>&nbsp;para ver lo que sucede cuando cancela su cuenta.</p>
<h2 id="section2">2. Inscripci&oacute;n en un curso y acceso de por vida</h2>
<p>&nbsp;</p>
<div class="alert alert-info">
<div class="content">Cuando se inscribe en un curso, le proporcionamos una licencia para verlo a trav&eacute;s de los Servicios de Udemy, pero para ning&uacute;n otro uso. No intente transferir ni revender los cursos de ninguna forma. Le concedemos una licencia de acceso de por vida, excepto cuando debamos desactivar el curso por motivos legales o relacionados con determinadas pol&iacute;ticas.</div>
</div>
<p>&nbsp;</p>
<p>De conformidad con nuestro&nbsp;<a href="https://www.udemy.com/terms/instructor/">Acuerdo de instructor</a>, cuando los instructores publican un curso en Udemy, proporcionan a Udemy la licencia para ofrecer a los estudiantes la correspondiente licencia para el curso. Esto significa que tenemos el derecho a sublicenciar el curso a los estudiantes que se inscriban en &eacute;l. Como estudiante, cuando se inscribe en un curso, ya sea gratis o de pago, Udemy le proporcionar&aacute; una licencia para ver el curso a trav&eacute;s de la plataforma de Udemy y los Servicios, y Udemy es el licenciatario registrado. Obtiene una licencia para disfrutar de los cursos, pero no se le venden. Esta licencia no le otorga ning&uacute;n derecho a revender el curso de ninguna manera; tampoco puede compartir la informaci&oacute;n de la cuenta con un comprador ni descargar el curso ilegalmente para despu&eacute;s compartirlo en sitios de descargas torrent.</p>
<p>Dicho en lenguaje legal y de forma m&aacute;s detallada, Udemy le ofrece (a usted como estudiante) una licencia limitada, intransferible y no exclusiva para acceder y ver tanto los cursos como el contenido relacionado para los que ha pagado todas las tarifas correspondientes, exclusivamente para sus fines personales, no comerciales y educativos, y solamente a trav&eacute;s de los Servicios, de conformidad con estas Condiciones y otras condiciones o restricciones asociadas con un curso en concreto o una funci&oacute;n espec&iacute;fica de nuestros Servicios. Todos los dem&aacute;s usos est&aacute;n expresamente prohibidos. No puede reproducir, redistribuir, transmitir, asignar, vender, emitir por radiodifusi&oacute;n, alquilar, compartir, prestar, modificar, adaptar, editar, crear trabajos derivados, sublicenciar o transferir de ninguna otra forma ning&uacute;n curso, a menos que obtenga nuestro permiso expl&iacute;cito para hacerlo en un acuerdo por escrito firmado por un representante autorizado de Udemy. Esta condici&oacute;n tambi&eacute;n se aplica al contenido al que accede a trav&eacute;s de nuestras API.</p>
<p>Por lo general, proporcionamos una licencia de acceso de por vida a nuestros estudiantes cuando se inscriben en un curso. Sin embargo, nos reservamos el derecho a revocar en cualquier momento cualquier licencia para acceder a los cursos y utilizarlos en el caso de que decidamos o debamos desactivar el acceso a un curso por motivos legales o relacionados con determinadas pol&iacute;ticas; por ejemplo, si el curso en el que se ha inscrito es el objeto de una queja de los derechos de autor, o bien si determinamos que el contenido infringe nuestras&nbsp;<a href="https://teach.udemy.com/trust-safety?lang=es">Directrices sobre confianza y seguridad</a>. El acceso de por vida no se aplica a las funciones y los servicios adicionales asociados con un curso: por ejemplo, los instructores pueden desactivar los subt&iacute;tulos traducidos de los cursos en cualquier momento, y un instructor puede decidir en cualquier momento que no seguir&aacute; proporcionando asistencia para el aprendizaje o los servicios de preguntas y respuestas relacionados con un curso. Seamos claros: el acceso de por vida se refiere al acceso al contenido del curso, pero no al instructor.</p>
<p>Los instructores no pueden conceder las licencias para sus cursos directamente a los estudiantes, y esta licencia directa se considerar&aacute; anulada, invalidada y una infracci&oacute;n directa de estas Condiciones.</p>
<h2 id="section3">3. Pagos, cr&eacute;ditos y reembolsos</h2>
<p>&nbsp;</p>
<div class="alert alert-info">
<div class="content">Cuando realiza un pago, acepta el uso de un m&eacute;todo de pago v&aacute;lido. Si no est&aacute; satisfecho con el curso, Udemy ofrece un periodo de 30 d&iacute;as para el reembolso o la devoluci&oacute;n del importe del curso en cr&eacute;ditos en el caso de la mayor&iacute;a de las compras de cursos.</div>
</div>
<p>&nbsp;</p>
<h3>3.1 Precios</h3>
<p>Los precios de los cursos en Udemy se determinan en funci&oacute;n de las condiciones descritas en el&nbsp;<a href="https://www.udemy.com/terms/instructor/">Acuerdo de instructor</a>&nbsp;y nuestra&nbsp;<a href="https://www.udemy.com/support/115013339928/">Pol&iacute;tica de precios y promociones</a>. En algunos casos, es posible que el precio de un curso ofertado en el sitio web de Udemy no coincida exactamente con el precio ofertado en nuestras aplicaciones para m&oacute;viles o TV; esto se debe a los sistemas de precios de los proveedores de la plataforma para m&oacute;viles y sus pol&iacute;ticas en cuanto a la implementaci&oacute;n de ventas y promociones.</p>
<p>Ejecutamos peri&oacute;dicamente promociones y ventas para nuestros cursos, y algunos cursos solo est&aacute;n disponibles a precios con descuento durante un determinado periodo de tiempo. El precio que se aplica a un curso ser&aacute; el precio vigente en el momento en que finalice la compra del curso (al pasar por caja). Es posible que cualquier precio ofertado para un curso espec&iacute;fico tambi&eacute;n sea diferente cuando ha iniciado sesi&oacute;n en su cuenta respecto al precio disponible para los usuarios que no est&aacute;n registrados o que no han iniciado sesi&oacute;n, porque algunas de nuestras promociones solo est&aacute;n disponibles para los usuarios nuevos.</p>
<p>Cuando ha iniciado sesi&oacute;n en su cuenta, la divisa que se muestra se basa en la ubicaci&oacute;n en la que se encontraba cuando cre&oacute; la cuenta. Cuando no ha iniciado sesi&oacute;n en su cuenta, la divisa de los precios que se muestra se basa en el pa&iacute;s en el que se encuentra. No permitimos que los usuarios vean los precios en otras divisas.</p>
<p>Si es un estudiante que se encuentra en un pa&iacute;s en el que se aplican los impuestos sobre ventas y uso, los impuestos sobre el consumo de bienes y servicios o el IVA (Impuesto sobre el Valor A&ntilde;adido) a las ventas al consumidor, asumimos la responsabilidad de recopilar y remitir dichos impuestos a las autoridades fiscales correspondientes. En determinados pa&iacute;ses, el precio que se muestra incluye dichos impuestos.</p>
<h3>3.2 Pagos</h3>
<p>Acepta pagar las tarifas de los cursos que compra, y nos autoriza a cargar el importe de dichas tarifas en su tarjeta de d&eacute;bito o cr&eacute;dito, o bien a procesarlo mediante cualquier otra forma de pago (como Boleto, SEPA, adeudo directo o monedero m&oacute;vil). Udemy colabora con socios externos de procesamiento de pagos para ofrecerle los m&eacute;todos de pago m&aacute;s c&oacute;modos de su pa&iacute;s y mantener su informaci&oacute;n de pago segura. Eche un vistazo a nuestra&nbsp;<a href="https://www.udemy.com/terms/privacy/">Pol&iacute;tica de privacidad</a>&nbsp;para obtener m&aacute;s informaci&oacute;n.</p>
<p>Cuando hace una compra, acepta que no debe utilizar un m&eacute;todo de pago no v&aacute;lido o no autorizado. Si se produce un error con su m&eacute;todo de pago, pero a&uacute;n as&iacute; obtiene acceso al curso en el que se ha inscrito, acepta pagarnos las tarifas correspondientes en el plazo de treinta (30) d&iacute;as a partir de la recepci&oacute;n de nuestra notificaci&oacute;n. Nos reservamos el derecho a desactivar el acceso a cualquier curso para el que no hayamos recibido los pagos correspondientes.</p>
<p>En algunos casos, podemos enviar cr&eacute;ditos a su cuenta. Estos cr&eacute;ditos se aplicar&aacute;n autom&aacute;ticamente al siguiente curso que compre en nuestro sitio web, pero no pueden utilizarse para las compras que se realicen a trav&eacute;s de nuestras aplicaciones para m&oacute;viles o TV. Los cr&eacute;ditos pueden caducar si no se utilizan en el periodo de tiempo especificado, y no tienen valor en met&aacute;lico.</p>
<h3>3.3 Reembolsos y cr&eacute;ditos</h3>
<p>Si el curso que compr&oacute; no es lo que esperaba, puede solicitar que Udemy le devuelva el importe del curso en cr&eacute;ditos o un reembolso en el plazo de 30 d&iacute;as a partir de la compra del curso. Nos reservamos el derecho a aplicar la devoluci&oacute;n del importe en cr&eacute;ditos o un reembolso, a nuestro exclusivo criterio, en funci&oacute;n de las capacidades de sus socios de procesamiento de pagos o la plataforma en la que compr&oacute; el curso (sitio web o aplicaciones para m&oacute;viles o TV). No podr&aacute; obtener los cr&eacute;ditos ni el reembolso si los solicita cuando se haya superado el plazo de tiempo l&iacute;mite de 30 d&iacute;as.</p>
<p>Para solicitar los cr&eacute;ditos o el reembolso, siga los pasos que se muestran&nbsp;<a href="https://www.udemy.com/support/229604248/">aqu&iacute;</a>. Tal como se describe en el&nbsp;<a href="https://www.udemy.com/terms/instructor/">Acuerdo de instructor</a>, los instructores aceptan que los estudiantes tienen el derecho a recibir estos cr&eacute;ditos o reembolsos.</p>
<p>A nuestro exclusivo criterio, si creemos que est&aacute; abusando de nuestra pol&iacute;tica de cr&eacute;ditos/reembolsos, nos reservamos el derecho a prohibir su cuenta y restringir su utilizaci&oacute;n futura de los Servicios. Si prohibimos su cuenta o desactivamos su acceso a un curso debido a la infracci&oacute;n que ha cometido de estas Condiciones o nuestras&nbsp;<a href="https://teach.udemy.com/trust-safety?lang=es">Directrices sobre confianza y seguridad</a>, no reunir&aacute; los requisitos para recibir cr&eacute;ditos o reembolsos.</p>
<h2 id="section4">4. Reglas de contenido y comportamiento</h2>
<p>&nbsp;</p>
<div class="alert alert-info">
<div class="content">Solo puede utilizar Udemy para fines legales. Asume la responsabilidad de todo el contenido que publica en nuestra plataforma. Debe lograr que las revisiones, las preguntas, las publicaciones, los cursos y cualquier otro contenido que cargue online cumplan nuestras&nbsp;<a href="https://teach.udemy.com/trust-safety?lang=es">Directrices sobre confianza y seguridad</a>&nbsp;y la ley, as&iacute; como respetar los derechos de propiedad intelectual de otros. Podemos prohibir su cuenta por faltas repetidas o graves. Si piensa que alguien est&aacute; infringiendo sus derechos de autor en nuestra plataforma, av&iacute;senos.</div>
</div>
<p>&nbsp;</p>
<p>No puede acceder a los Servicios ni utilizarlos, ni crear una cuenta para fines que no sean legales. Su utilizaci&oacute;n de los Servicios y su comportamiento en nuestra plataforma debe cumplir las leyes locales o nacionales, o bien las normativas vigentes de su pa&iacute;s. Asume toda la responsabilidad respecto al conocimiento y el cumplimiento de dichas leyes y normativas vigentes. No puede acceder a nuestros Servicios si pertenece a un territorio en el que las empresas de EE. UU. tienen prohibido hacer negocios (como Cuba, Ir&aacute;n, Corea del Norte, Sud&aacute;n o Siria), o bien si el gobierno de EE. UU. le ha incluido en una lista de ciudadanos especialmente designados, personas no autorizadas o entidades no autorizadas.</p>
<p>Si es un estudiante, los Servicios le permiten formular preguntas a los instructores de los cursos en los que est&aacute; inscrito, as&iacute; como publicar rese&ntilde;as de los cursos. Para determinados cursos, el instructor le invita a enviar contenido, como &ldquo;deberes&rdquo; o ex&aacute;menes. No publique ni env&iacute;e contenido que no sea suyo.</p>
<p>Si es un instructor, puede enviar cursos para su publicaci&oacute;n en la plataforma. Tambi&eacute;n puede comunicarse con los estudiantes que se han inscrito en sus cursos. En ambos casos, debe cumplir la ley y respetar los derechos de los dem&aacute;s: no puede publicar cursos, preguntas, respuestas, rese&ntilde;as u otro contenido que infrinja las leyes locales o nacionales, o bien las normativas vigentes de su pa&iacute;s. Asume toda la responsabilidad respecto a los cursos y el contenido que publica, as&iacute; como de las acciones que lleva a cabo y sus consecuencias, a trav&eacute;s de la plataforma y los Servicios. Aseg&uacute;rese de que entiende todas las restricciones relacionadas con los derechos de autor incluidas en el&nbsp;<a href="https://www.udemy.com/terms/instructor/">Acuerdo de instructor</a>&nbsp;antes de enviar un curso para su publicaci&oacute;n en Udemy.</p>
<p>Si recibe una notificaci&oacute;n que indica que su curso o contenido infringe la ley o los derechos de otros (por ejemplo, si se ha establecido que infringe la propiedad intelectual o los derechos de imagen de otros, o bien est&aacute; relacionado con una actividad ilegal), o bien descubrimos que su contenido o comportamiento infringe nuestras&nbsp;<a href="https://teach.udemy.com/trust-safety?lang=es">Directrices sobre confianza y seguridad</a>, o bien creemos que su contenido o comportamiento infringe la ley o es inapropiado o cuestionable (por ejemplo, si se hace pasar por otra persona), podemos eliminar su contenido de nuestra plataforma. Udemy cumple las leyes de derechos de autor. Eche un vistazo a nuestra&nbsp;<a href="https://www.udemy.com/terms/copyright/">Pol&iacute;tica de propiedad intelectual</a>&nbsp;para obtener m&aacute;s informaci&oacute;n.</p>
<p>Udemy puede aplicar estas Condiciones y nuestras&nbsp;<a href="https://teach.udemy.com/trust-safety?lang=es">Directrices sobre confianza y seguridad</a>&nbsp;a su exclusivo criterio. Podemos cancelar o suspender su permiso para utilizar nuestra plataforma y nuestros Servicios, o bien prohibir su cuenta en cualquier momento con o sin previo aviso, por los siguientes motivos: si se produce cualquier infracci&oacute;n de estas Condiciones, si no paga las tarifas correspondientes a su debido tiempo, a petici&oacute;n de las autoridades legales o agencias gubernamentales, por periodos extensos de inactividad, por problemas t&eacute;cnicos inesperados, o bien si sospechamos que lleva a cabo actividades fraudulentas o ilegales. Cuando se lleve a cabo dicha cancelaci&oacute;n, podemos eliminar su cuenta y sus contenidos, y podemos evitar que vuelva a acceder a las plataformas y utilizar nuestros Servicios. Puede que su contenido a&uacute;n est&eacute; disponible en las plataformas incluso si se ha cancelado o suspendido su cuenta. Acepta que no asumimos ninguna responsabilidad hacia usted ni ning&uacute;n tercero por la cancelaci&oacute;n de su cuenta, la eliminaci&oacute;n de su contenido o el bloqueo de su acceso a nuestras plataformas y servicios.</p>
<p>Si uno de nuestros instructores ha publicado un curso que infringe sus derechos de autor o de marcas, av&iacute;senos. De conformidad con nuestro&nbsp;<a href="https://www.udemy.com/terms/instructor/">Acuerdo de instructor</a>, solicitamos a nuestros instructores que cumplan la ley y respeten los derechos de propiedad intelectual de otros. Para obtener m&aacute;s informaci&oacute;n sobre como presentar una reclamaci&oacute;n sobre una infracci&oacute;n de los derechos de autor o de marcas, consulte nuestra&nbsp;<a href="https://www.udemy.com/terms/copyright/">Pol&iacute;tica de propiedad intelectual</a>.</p>
<h2 id="section5">5. Derechos de Udemy respecto al contenido que publica</h2>
<p>&nbsp;</p>
<div class="alert alert-info">
<div class="content">Mantiene la propiedad del contenido que publica en nuestra plataforma, incluidos sus cursos. Tenemos autorizaci&oacute;n para compartir su contenido con cualquier persona a trav&eacute;s de cualquier medio de comunicaci&oacute;n, incluida la promoci&oacute;n de su contenido mediante la publicidad en otros sitios web.</div>
</div>
<p>&nbsp;</p>
<p>El contenido que publica como estudiante o instructor (incluidos los cursos) sigue siendo de su propiedad. Al publicar cursos y otro contenido, autoriza a Udemy a reutilizarlos y compartirlos, pero no pierde los derechos de propiedad que pueda tener sobre su contenido. Si es un instructor, aseg&uacute;rese de comprender las condiciones de la licencia del curso detalladas en el&nbsp;<a href="https://www.udemy.com/terms/instructor/">Acuerdo de instructor</a>.</p>
<p>Al publicar comentarios, preguntas y rese&ntilde;as, y cuando nos env&iacute;a ideas y sugerencias sobre nuevas funciones o mejoras, autoriza a Udemy a utilizar y compartir este contenido con cualquier otra persona, as&iacute; como distribuirlo y promocionarlo en cualquier plataforma o medio de comunicaci&oacute;n, y modificarlo o editarlo de la forma que creamos conveniente. En lenguaje legal, al enviar o publicar contenido en las plataformas o a trav&eacute;s de ellas, nos concede una licencia mundial, no exclusiva y libre de regal&iacute;as (con el derecho a sublicenciarlo) para utilizar, copiar, reproducir, procesar, adaptar, modificar, publicar, transmitir, mostrar y distribuir su contenido en cualquier medio de comunicaci&oacute;n o a trav&eacute;s de cualquier m&eacute;todo de distribuci&oacute;n (existente o desarrollado posteriormente). Esto incluye hacer que su contenido est&eacute; disponible para otras empresas, organizaciones o individuos asociados con Udemy para la redifusi&oacute;n, radiodifusi&oacute;n, distribuci&oacute;n o publicaci&oacute;n del contenido en otros medios de comunicaci&oacute;n. Declara y garantiza que tiene la potestad, la autoridad y todos los derechos necesarios para autorizarnos a utilizar todo el contenido que env&iacute;e. Tambi&eacute;n acepta todos estos usos de su contenido sin recibir a cambio ning&uacute;n tipo de compensaci&oacute;n econ&oacute;mica.</p>
<h2 id="section6">6. Utilizaci&oacute;n de Udemy por su cuenta y riesgo</h2>
<p>&nbsp;</p>
<div class="alert alert-info">
<div class="content">Cualquier persona puede utilizar Udemy para crear y publicar cursos, y permitimos que instructores y estudiantes interact&uacute;en para la ense&ntilde;anza y el aprendizaje. Como en el caso de otras plataformas en las que las personas pueden publicar contenido e interactuar, a veces las cosas pueden salir mal, y utilizar&aacute; Udemy por su cuenta y riesgo.</div>
</div>
<p>&nbsp;</p>
<p>Udemy permite a cualquiera crear y compartir cursos educativos en cualquier parte del mundo. Albergamos m&aacute;s de 100.000 cursos en nuestra tienda virtual de aprendizaje online. Nuestro modelo de plataforma supone que no revisamos ni editamos los cursos por cuestiones legales ni estamos en posici&oacute;n de determinar la legalidad del contenido de un curso. No llevamos a cabo un control editorial de los cursos que est&aacute;n disponibles en la plataforma y, por lo tanto, no garantizamos de ninguna manera la fiabilidad, validez, precisi&oacute;n o autenticidad de los cursos. Si se inscribe en un curso, depende de la informaci&oacute;n proporcionada por el instructor por su cuenta y riesgo.</p>
<p>Al utilizar los Servicios, puede exponerse a contenido que considere ofensivo, indecente o cuestionable. En la medida m&aacute;xima permitida por la ley vigente, Udemy no asume ninguna responsabilidad respecto a su acceso a cualquier curso o su inscripci&oacute;n en &eacute;l. Esto tambi&eacute;n se aplica a todos aquellos cursos relacionados con la salud, el bienestar y el ejercicio f&iacute;sico. Reconoce los riesgos y peligros inherentes a la naturaleza intensa de este tipo de cursos; por eso, al inscribirse en ellos, elige asumir estos riesgos de forma voluntaria, incluidos los riesgos de enfermedad, lesiones f&iacute;sicas, discapacidad o muerte. Asume toda la responsabilidad respecto a las decisiones que tome antes, durante y despu&eacute;s de su inscripci&oacute;n en un curso.</p>
<p>Cuando interact&uacute;a directamente con un estudiante o instructor, debe tener cuidado con el tipo de informaci&oacute;n personal que comparte. No controlamos lo que los estudiantes e instructores hacen con la informaci&oacute;n que obtienen de otros usuarios en la plataforma. Por su propia seguridad, no debe compartir su direcci&oacute;n de correo electr&oacute;nico ni ninguna otra informaci&oacute;n personal propia.</p>
<p>No contratamos ni empleamos a los instructores, ni asumimos ning&uacute;n tipo de responsabilidad por las interacciones que se producen entre instructores y estudiantes. Tampoco asumimos ning&uacute;n tipo de responsabilidad ante los da&ntilde;os, disputas, reclamaciones, p&eacute;rdidas o lesiones de cualquier tipo que puedan surgir o relacionarse con la conducta de los instructores o estudiantes.</p>
<p>Cuando utiliza nuestros Servicios, encontrar&aacute; enlaces a otros sitios web que no son de nuestra propiedad ni controlamos. No asumimos ning&uacute;n tipo de responsabilidad respecto al contenido ni ning&uacute;n otro aspecto de estos sitios de terceros, incluida la recopilaci&oacute;n que hagan de su informaci&oacute;n. Tambi&eacute;n debe leer sus condiciones y pol&iacute;ticas de privacidad.</p>
<h2 id="section7">7. Derechos de Udemy</h2>
<p>&nbsp;</p>
<div class="alert alert-info">
<div class="content">Somos los propietarios de la plataforma y los Servicios de Udemy, incluidos el sitio web, los servicios y aplicaciones existentes o futuras, y elementos como nuestros logotipos, las API, el c&oacute;digo y el contenido creado por nuestros empleados. No puede manipular estos elementos ni utilizarlos sin autorizaci&oacute;n.</div>
</div>
<p>&nbsp;</p>
<p>Todos los derechos, t&iacute;tulos e intereses relacionados con la plataforma y los Servicios de Udemy, incluidos nuestro sitio web, nuestros servicios y aplicaciones existentes o futuras, as&iacute; como nuestras API, nuestras bases de datos y el contenido que nuestros empleados o socios env&iacute;an o proporcionan a trav&eacute;s de nuestros Servicios (excluidos el contenido proporcionado por los instructores y estudiantes) son y seguir&aacute;n siendo propiedad de Udemy y sus licenciatarios. Nuestras plataformas y servicios est&aacute;n protegidos por derechos de autor, marca registrada y otras leyes tanto de Estados Unidos como de otros pa&iacute;ses. Nada le confiere el derecho a utilizar el nombre de Udemy ni las marcas registradas, los logotipos, los nombres de dominio y otras caracter&iacute;sticas distintivas de la marca de Udemy. Todos los comentarios o sugerencias que proporcione en relaci&oacute;n con Udemy o los Servicios son completamente voluntarios, y tendremos total libertad para hacer uso de dichos comentarios y sugerencias de la manera que veamos conveniente y sin incurrir en ning&uacute;n tipo de obligaci&oacute;n hacia usted.</p>
<p>No puede hacer ninguna de las siguientes acciones al acceder o utilizar la plataforma y los Servicios de Udemy:</p>
<ul>
<li>Acceder a las &aacute;reas no p&uacute;blicas de la plataforma, los sistemas inform&aacute;ticos de Udemy o los sistemas de distribuci&oacute;n t&eacute;cnica de los proveedores de servicios de Udemy, ni tampoco manipularlos o utilizarlos.</li>
<li>Desactivar, interferir o intentar burlar cualquiera de las funciones de las plataformas relacionadas con la seguridad, as&iacute; como explorar, analizar y probar la vulnerabilidad de nuestros sistemas.</li>
<li>Copiar, modificar, crear un trabajo derivado, aplicar ingenier&iacute;a inversa, desarmar o intentar de alguna otra forma descubrir cualquier c&oacute;digo fuente o contenido de la plataforma o los Servicios de Udemy.</li>
<li>Acceder o buscar, o bien intentar acceder o buscar (de forma autom&aacute;tica o de cualquier otra forma), nuestra plataforma de cualquier otra manera que no sea a trav&eacute;s de nuestras funcionalidades de b&uacute;squeda disponibles actualmente y que se proporcionan a trav&eacute;s de nuestro sitio web y nuestras aplicaciones m&oacute;viles o API (y solo de conformidad con las condiciones de dichas API). No puede utilizar m&eacute;todos de extracci&oacute;n de datos (&ldquo;scraping&rdquo;), ara&ntilde;as, robots o cualquier otro medio automatizado de cualquier otro tipo para acceder a los Servicios.</li>
<li>Utilizar de cualquier forma los Servicios para enviar informaci&oacute;n con identificaci&oacute;n de origen manipulada, enga&ntilde;osa o falsa (como el env&iacute;o de comunicaciones de correo electr&oacute;nico que simulen falsamente ser de Udemy); o bien interferir o interrumpir (o intentar interferir o interrumpir) el acceso de cualquier usuario, host o red, incluidos, entre otros, el env&iacute;o de virus, sobrecargas, saturaciones, el env&iacute;o de spam o bombardeo de correos electr&oacute;nicos a las plataformas o servicios, o bien interferir o crear una carga innecesaria de cualquier otra manera en los Servicios.</li>
</ul>
<h2 id="section8">8. Otras Condiciones legales</h2>
<p>&nbsp;</p>
<div class="alert alert-info">
<div class="content">Estas Condiciones son muy similares a cualquier otro contrato, e incluyen t&eacute;rminos aburridos pero importantes que nos protegen de las innumerables cosas que pueden pasar, y que clarifican la relaci&oacute;n legal que se establece entre usted y nosotros.</div>
</div>
<p>&nbsp;</p>
<h3>8.1 Acuerdo vinculante</h3>
<p>Acepta que al registrarse y acceder a nuestros Servicios y utilizarlos, confirma que establecer&aacute; un contrato legalmente vinculante con Udemy. Si no acepta estas Condiciones, no se registre ni acceda o utilice de cualquier otra forma nuestros Servicios.</p>
<p>Si es un instructor que acepta estas Condiciones y utiliza nuestros Servicios en nombre de una empresa, organizaci&oacute;n, gobierno o cualquier otra entidad legal, se le considerar&aacute; el representante y garantiza que tiene autorizaci&oacute;n para ello.</p>
<p>Toda versi&oacute;n de estas Condiciones de uso en un idioma distinto del ingl&eacute;s se facilita para su comodidad. Por tanto, confirma y acepta que la versi&oacute;n en el idioma ingl&eacute;s prevalecer&aacute; si existieran discrepancias.</p>
<p>Estas Condiciones (incluidos todos los acuerdos y pol&iacute;ticas vinculadas a estas Condiciones) constituyen el acuerdo completo entre usted y nosotros (que incluye, si es un instructor, el&nbsp;<a href="https://www.udemy.com/terms/instructor/">Acuerdo de instructor</a>&nbsp;y la&nbsp;<a href="https://www.udemy.com/support/115013339928/">Pol&iacute;tica de precios y promociones</a>).</p>
<p>Si se confirma que cualquier disposici&oacute;n de estas Condiciones no es v&aacute;lida o inaplicable por la ley vigente, entonces esa provisi&oacute;n se sustituir&aacute; por otra v&aacute;lida y aplicable que se ajuste mejor a la intenci&oacute;n de la provisi&oacute;n original, y el resto de las Condiciones seguir&aacute;n en vigor.</p>
<p>Incluso si en alg&uacute;n caso ejercemos nuestros derechos con demora o no los ejercemos, esto no significa que renunciamos a nuestros derechos incluidos en estas Condiciones, y puede que decidamos ejercerlos en el futuro. Si decidimos renunciar a algunos de nuestros derechos en un caso determinado, esto no significa que renunciamos a todos nuestros derechos en general o en el futuro.</p>
<p>Las siguientes secciones seguir&aacute;n vigentes tras el vencimiento o la rescisi&oacute;n de estas Condiciones: secciones 2 (Inscripci&oacute;n en un curso y acceso de por vida), 5 (Derechos de Udemy respecto al contenido que publica), 6 (Utilizaci&oacute;n de Udemy por su cuenta y riesgo), 7 (Derechos de Udemy), 8 (Otras Condiciones legales) y 9 (Resoluci&oacute;n de conflictos).</p>
<h3>8.2 Descargos de responsabilidad</h3>
<p>Puede que en alg&uacute;n momento nuestra plataforma no est&eacute; disponible, bien por tareas de mantenimiento planificado, o bien porque haya alg&uacute;n problema en el sitio. Puede que uno de nuestros instructores realice afirmaciones enga&ntilde;osas en su curso. Puede que tambi&eacute;n detectemos problemas de seguridad. Estos son solo algunos ejemplos. Acepta que no emprender&aacute; ninguna acci&oacute;n legal contra nosotros en el caso de que se produzcan este tipo de problemas y las cosas no vayan bien. Dicho en lenguaje legal y de forma m&aacute;s detallada,&nbsp;<strong>los Servicios y su contenido se proporcionan &ldquo;tal cual&rdquo; y &ldquo;seg&uacute;n disponibilidad&rdquo;. Nosotros (y nuestros afiliados, proveedores, socios y agentes) no formulamos ninguna declaraci&oacute;n ni garant&iacute;a sobre la idoneidad, fiabilidad, disponibilidad, puntualidad, seguridad, ausencia de errores o precisi&oacute;n de los Servicios o su contenido; asimismo, negamos expresamente cualesquiera garant&iacute;as y condiciones (expresas o impl&iacute;citas), incluidas las garant&iacute;as de comerciabilidad, idoneidad para un prop&oacute;sito en particular, t&iacute;tulo o no infracci&oacute;n. Nosotros (y nuestros afiliados, proveedores, socios y agentes) no formulamos ninguna garant&iacute;a de que obtendr&aacute; resultados espec&iacute;ficos por el uso de los Servicios. Utiliza los Servicios (incluido cualquier contenido) totalmente por su cuenta y riesgo. Algunas jurisdicciones no permiten la exclusi&oacute;n de las garant&iacute;as impl&iacute;citas, por lo que es posible que algunas de las exclusiones anteriores no se apliquen en su caso.</strong></p>
<p>Podemos decidir, en cualquier momento y por cualquier motivo, que algunas funciones de los Servicios dejen de estar disponibles. Bajo ninguna circunstancia se considerar&aacute; a Udemy o a sus afiliados, proveedores, socios o agentes responsables de cualesquiera da&ntilde;os que se produzcan debido a dichas interrupciones o a la falta de disponibilidad de dichas funciones.</p>
<p>No asumimos ning&uacute;n tipo de responsabilidad por la demora o el fallo en el rendimiento de cualquiera de nuestros Servicios debido a eventos que est&eacute;n fuera de nuestro control razonable, como actos de guerra, hostilidad o sabotaje, desastres naturales, interrupciones en el suministro el&eacute;ctrico y de Internet o las telecomunicaciones, o bien restricciones gubernamentales.</p>
<h3>8.3 Limitaci&oacute;n de responsabilidad</h3>
<p>La utilizaci&oacute;n de nuestros Servicios conlleva riesgos inherentes: por ejemplo, si se inscribe en un curso de salud y bienestar como yoga, y se lesiona. Acepta completamente estos riesgos y que no emprender&aacute; ninguna acci&oacute;n legal por estos da&ntilde;os contra nosotros, incluso si sufre p&eacute;rdidas o da&ntilde;os debido a la utilizaci&oacute;n de nuestra plataforma y nuestros Servicios. Dicho en lenguaje legal y de forma m&aacute;s detallada,&nbsp;<strong>en la medida m&aacute;xima permitida por la ley, nosotros (y nuestras empresas del grupo, proveedores, socios y agentes) no asumiremos ning&uacute;n tipo de responsabilidad por aquellos da&ntilde;os indirectos, incidentales, punitivos o consecuentes (incluidos la p&eacute;rdida de datos, ingresos, beneficios u oportunidades de negocio, o bien cualquier lesi&oacute;n personal o muerte) que puedan surgir por contrato, garant&iacute;a, agravio, responsabilidad de productos o de cualquier otra forma, e incluso si se nos ha notificado previamente la posibilidad de que esos da&ntilde;os se produzcan. Nuestra responsabilidad (y la responsabilidad de cada una de las empresas de nuestro grupo, proveedores, socios y agentes) ante usted o cualquier otro tercero bajo cualquier circunstancia se limita a la cantidad de cien d&oacute;lares (100 USD) o el importe que nos haya pagado en el plazo de doce (12) meses previo a que ocurriera el evento que motiva sus reclamaciones. Algunas jurisdicciones no permiten la exclusi&oacute;n o limitaci&oacute;n de los da&ntilde;os consecuentes o incidentales, por lo que es posible que algunas de las afirmaciones anteriores no se apliquen en su caso.</strong></p>
<h3>8.4 Indemnizaci&oacute;n</h3>
<p>Si se comporta de una forma que d&eacute; lugar a problemas legales para nosotros, podemos tomar acciones legales contra usted. Acepta indemnizar, defender (si as&iacute; lo solicitamos) y mantener indemne a Udemy, las empresas de nuestro grupo y sus gestores, directores, proveedores, socios y agentes frente a reclamaciones, demandas, p&eacute;rdidas o gastos de terceros (incluidos los honorarios razonables de abogados) que surjan por (a) el contenido que publica o env&iacute;a, (b) su utilizaci&oacute;n de los Servicios, (c) su infracci&oacute;n de estas Condiciones o (d) su infracci&oacute;n de cualesquiera derechos de un tercero. Sus obligaciones de indemnizaci&oacute;n seguir&aacute;n vigentes tras la rescisi&oacute;n de estas Condiciones y la utilizaci&oacute;n que haga de los Servicios.</p>
<h3>8.5 Ley vigente y jurisdicci&oacute;n</h3>
<p>Estas Condiciones se rigen por las leyes del Estado de California (EE. UU), dejando sin efecto a ninguna elecci&oacute;n de la ley o conflicto de los principios de la ley. En aquellos casos en los que la secci&oacute;n &ldquo;Resoluci&oacute;n de conflictos&rdquo; que aparece a continuaci&oacute;n no se aplica, tanto usted como nosotros aceptamos la jurisdicci&oacute;n y la competencia exclusivas de los tribunales federales y estatales ubicados en San Francisco, California, EE. UU.</p>
<h3>8.6 Acciones legales y avisos</h3>
<p>Ninguna de las partes podr&aacute; iniciar una acci&oacute;n, independientemente de su forma, en virtud del presente Acuerdo m&aacute;s de un (1) a&ntilde;o despu&eacute;s de la fecha en que surge el derecho de acci&oacute;n.</p>
<p>Cualquier aviso o cualquier otra comunicaci&oacute;n que deba llevarse a cabo por la presente se realizar&aacute; por escrito y por correo certificado con acuse de recibo, o bien por correo electr&oacute;nico (nosotros utilizaremos la direcci&oacute;n de correo electr&oacute;nico asociada con su cuenta, y usted utilizar&aacute; la direcci&oacute;n notices@udemy.com).</p>
<h3>8.7 Relaci&oacute;n entre nosotros</h3>
<p>Tanto usted como nosotros aceptamos que entre nosotros no existe una relaci&oacute;n de empresa conjunta, asociaci&oacute;n, empleo, contratista o agencia.</p>
<h3>8.8 Asignaci&oacute;n prohibida</h3>
<p>No puede asignar ni transferir estas Condiciones (ni los derechos y licencias que se conceden en virtud de las mismas). Por ejemplo, si ha registrado una cuenta como empleado de una empresa, su cuenta no puede transferirse a otro empleado. Nosotros podemos asignar estas Condiciones (o los derechos y licencias que se conceden en virtud de las mismas) a otra empresa o persona sin restricciones. Nada de lo que se incluye en estas Condiciones confiere ning&uacute;n derecho, beneficio o recurso a cualquier persona o entidad externa. Acepta que su cuenta es intransferible y que todos los derechos relacionados con su cuenta o estas Condiciones finalizan cuando fallece.</p>
<h2 id="section9">9. Resoluci&oacute;n de conflictos</h2>
<p>&nbsp;</p>
<div class="alert alert-info">
<div class="content">Si existe un conflicto, nuestro&nbsp;<a href="https://www.udemy.com/support/">Equipo de soporte</a>&nbsp;estar&aacute; encantado de ayudarle a resolverlo. Si esta medida no funciona y vive en Estados Unidos o Canad&aacute;, sus opciones se limitan a acudir a los juzgados de primera instancia o presentar una reclamaci&oacute;n mediante arbitraje vinculante. No puede presentar la reclamaci&oacute;n en otro tribunal ni participar en una acci&oacute;n de grupo no individual contra nosotros.</div>
</div>
<p>&nbsp;</p>
<p><strong>La secci&oacute;n Resoluci&oacute;n de conflictos solo se aplica si vive en Estados Unidos o Canad&aacute;.</strong>&nbsp;La mayor&iacute;a de los conflictos pueden resolverse, por lo tanto, antes de comenzar un proceso jur&iacute;dico oficial, intente ponerse en contacto con nuestro&nbsp;<a href="https://www.udemy.com/support/">Equipo de soporte</a>.</p>
<h3>9.1 Juzgados de primera instancia</h3>
<p>Tanto usted como nosotros podemos presentar una reclamaci&oacute;n en los juzgados de primera instancia en (a) San Francisco, California, (b) el pa&iacute;s en el que vive, o bien (c) cualquier otra ubicaci&oacute;n que acordemos entre nosotros, siempre que dicho tribunal re&uacute;na los requisitos necesarios para presentar la reclamaci&oacute;n.</p>
<h3>9.2 Arbitraje</h3>
<p>Si no podemos resolver nuestro conflicto de forma amistosa, tanto usted como Udemy aceptan la resoluci&oacute;n de cualquier reclamaci&oacute;n relacionada con estas Condiciones (o nuestras otras condiciones legales) a trav&eacute;s de un proceso de arbitraje final y vinculante, independientemente del tipo de reclamaci&oacute;n o teor&iacute;a jur&iacute;dica. Si uno de nosotros presenta una reclamaci&oacute;n en un tribunal que debe someterse a arbitraje y la otra parte lo rechaza, la otra parte puede solicitar que un tribunal fuerce a ambas partes a iniciar dicho arbitraje (arbitraje obligatorio). Cualquiera de las dos partes puede solicitar que un tribunal detenga un proceso judicial mientras haya un proceso de arbitraje en curso.</p>
<h3>9.3 Proceso de arbitraje</h3>
<p>Cualquier conflicto relacionado con una reclamaci&oacute;n de menos de 10 000 USD debe resolverse exclusivamente a trav&eacute;s de un proceso de arbitraje sin comparecencia vinculante. La parte que selecciona el arbitraje debe iniciar el procedimiento mediante el registro de una demanda de arbitraje en la Asociaci&oacute;n de Arbitraje de los Estados Unidos (AAA, del ingl&eacute;s &ldquo;American Arbitration Association&rdquo;). El proceso de arbitraje se regir&aacute; por las normas de arbitraje comercial (&ldquo;Commercial Arbitration Rules&rdquo;), el protocolo de proceso para el consumidor (&ldquo;Consumer Due Process Protocol&rdquo;) y los procedimientos complementarios de soluci&oacute;n de conflictos en materia de consumo (&ldquo;Supplementary Procedures for Resolution of Consumer-Related Disputes&rdquo;) de la AAA. Tanto usted como nosotros acordamos que se aplicar&aacute;n las siguientes reglas a los procedimientos: (a) el arbitraje se llevar&aacute; cabo por tel&eacute;fono, online o solamente a trav&eacute;s de env&iacute;os por escrito (a elecci&oacute;n de la parte que busca las medidas correctivas); (b) el arbitraje no debe incluir la comparecencia personal de las partes o los testigos (a menos que usted y nosotros acordemos lo contrario); y (c) el laudo dictado por el &aacute;rbitro podr&aacute; presentarse en cualquier tribunal con jurisdicci&oacute;n competente. Los conflictos relacionados con una reclamaci&oacute;n de m&aacute;s de 10 000 USD deber&aacute;n resolverse por las reglas de la AAA respecto a si la audiencia de arbitraje debe realizarse en persona.</p>
<h3>9.4 Se proh&iacute;be la participaci&oacute;n en acciones de grupo</h3>
<p>Tanto usted como nosotros aceptamos que solo podemos presentar reclamaciones contra el otro de forma individual. Esto significa lo siguiente: (a) ninguno de nosotros puede presentar una reclamaci&oacute;n como parte demandante o miembro de clase en una acci&oacute;n de grupo, acci&oacute;n consolidada o acci&oacute;n representativa; (b) un &aacute;rbitro no puede combinar las reclamaciones de varias personas en un solo caso (o presidir cualquier acci&oacute;n consolidada, de clase o representativa); y (c) la decisi&oacute;n o el laudo de un &aacute;rbitro en el caso de una persona solo puede tener un impacto en dicho usuario, no en otros usuarios, y no se puede utilizar para tomar una decisi&oacute;n respecto a los conflictos de otros usuarios. Si un tribunal decide que esta cl&aacute;usula (&ldquo;Se proh&iacute;be la participaci&oacute;n en acciones de grupo&rdquo;) no es aplicable o v&aacute;lida, esta secci&oacute;n &ldquo;Resoluci&oacute;n de conflictos&rdquo; se considerar&aacute; anulada e invalidada, pero el resto de las Condiciones seguir&aacute;n en vigor.</p>
<h3>9.5 Cambios</h3>
<p>Independientemente de lo estipulado en la secci&oacute;n &ldquo;Actualizaci&oacute;n de estas Condiciones&rdquo; que aparece a continuaci&oacute;n, si Udemy realiza alg&uacute;n cambio en la secci&oacute;n &ldquo;Resoluci&oacute;n de conflictos&rdquo; despu&eacute;s de la fecha en la que confirm&oacute; su aceptaci&oacute;n de estas Condiciones, puede rechazar este cambio; para ello, debe proporcionar a Udemy un aviso por escrito en el que se indique este rechazo. Puede enviar este aviso por correo postal o entregarlo manualmente en la siguiente direcci&oacute;n: Udemy, Inc. Attn: Legal, 600 Harrison Street, 3rd Floor, San Francisco, CA 94107; o bien, puede enviar un correo electr&oacute;nico desde la direcci&oacute;n asociada con su cuenta a: notices@udemy.com. El env&iacute;o debe realizarse en el plazo de 30 d&iacute;as a partir de la fecha de entrada en vigor de dicho cambio, que aparece en la frase &ldquo;se actualizaron por &uacute;ltima vez el&rdquo; que aparece anteriormente. Para que pueda ser efectivo, el aviso debe incluir su nombre completo e indicar claramente su intenci&oacute;n de rechazar dichos cambios en la secci&oacute;n &ldquo;Resoluci&oacute;n de conflictos&rdquo;. Al rechazar los cambios, acepta que arbitrar&aacute; cualquier conflicto entre usted y Udemy de conformidad con las provisiones incluidas en la secci&oacute;n &ldquo;Resoluci&oacute;n de conflictos&rdquo; a partir de la fecha en la que indic&oacute; su aceptaci&oacute;n de estas Condiciones.</p>
<h2 id="section10">10. Actualizaci&oacute;n de estas Condiciones</h2>
<p>De vez en cuando, puede que actualicemos estas Condiciones para clarificar nuestras pr&aacute;cticas o reflejar pr&aacute;cticas nuevas o diferentes (por ejemplo, cuando a&ntilde;adimos funciones nuevas), y Udemy se reserva el derecho, a su exclusivo criterio, de modificar o realizar cambios en estas Condiciones en cualquier momento. Si realizamos un cambio material, se lo notificaremos por uno de los medios principales: por ejemplo, envi&aacute;ndole un aviso por correo electr&oacute;nico a la direcci&oacute;n especificada en su cuenta o mediante de la publicaci&oacute;n del aviso a trav&eacute;s de nuestros Servicios. A menos que se indique lo contrario, las modificaciones entrar&aacute;n en vigor el d&iacute;a que se publiquen.</p>
<p>Si contin&uacute;a utilizando los Servicios despu&eacute;s de la entrada en vigor de los cambios, confirmar&aacute; as&iacute; que acepta dichos cambios. Las Condiciones revisadas sustituir&aacute;n a todas las Condiciones indicadas anteriormente.</p>
<h2 id="section11">11. C&oacute;mo puede ponerse en contacto con nosotros</h2>
<p>La mejor manera de ponerse en contacto con nosotros es a trav&eacute;s del&nbsp;<a href="https://www.udemy.com/support/">Equipo de soporte</a>. Estaremos encantados de que nos comunique sus preguntas, preocupaciones y comentarios sobre nuestros Servicios.</p>
<p>Gracias por ense&ntilde;ar y aprender con nosotros. &iexcl;Desate su potencial!</p>



				</div>
			</div>
		</div>
	</section>
	<!-- Intro section end -->


@stop

@section('scripts')

@stop



